local M = {}

function M.setup(highlight, palette)
	highlight("MiniCompletionActiveParameter", { underline = true })
	highlight("MiniCursorword", { underline = true })
	highlight("MiniCursorwordCurrent", { underline = true })
	highlight("MiniIndentscopeSymbol", { fg = palette.gray })
	highlight("MiniIndentscopePrefix", { nocombine = true }) -- Make it invisible
	highlight("MiniJump", { bg = palette.purple, fg = palette.bg })
	highlight("MiniJump2dSpot", { fg = palette.orange, bold = true, nocombine = true })
	highlight("MiniStarterCurrent", { nocombine = true })
	highlight("MiniStarterFooter", { fg = palette.yellow, italic = true })
	highlight("MiniStarterHeader", { fg = palette.blue })
	highlight("MiniStarterInactive", { fg = palette.gray, italic = true })
	highlight("MiniStarterItem", { fg = palette.fg })
	highlight("MiniStarterItemBullet", { fg = palette.gray })
	highlight("MiniStarterItemPrefix", { fg = palette.yellow })
	highlight("MiniStarterSection", { fg = palette.cyan })
	highlight("MiniStarterQuery", { fg = palette.green })
	highlight("MiniStatuslineDevinfo", { fg = palette.gray, bg = palette.dark_gray })
	highlight("MiniStatuslineFileinfo", { fg = palette.gray, bg = palette.dark_gray })
	highlight("MiniStatuslineFilename", { fg = palette.gray, bg = palette.darker_gray })
	highlight("MiniStatuslineInactive", { fg = palette.gray, bg = palette.bg })
	highlight("MiniStatuslineModeCommand", { fg = palette.bg, bg = palette.yellow, bold = true })
	highlight("MiniStatuslineModeInsert", { fg = palette.bg, bg = palette.green, bold = true })
	highlight("MiniStatuslineModeNormal", { fg = palette.bg, bg = palette.blue, bold = true })
	highlight("MiniStatuslineModeOther", { fg = palette.bg, bg = palette.cyan, bold = true })
	highlight("MiniStatuslineModeReplace", { fg = palette.bg, bg = palette.red, bold = true })
	highlight("MiniStatuslineModeVisual", { fg = palette.bg, bg = palette.purple, bold = true })

	highlight("MiniSurround", { bg = palette.orange, fg = palette.bg })
	highlight("MiniTablineCurrent", { fg = palette.fg, bg = palette.dark_gray })
	highlight("MiniTablineFill", { bg = palette.black })
	highlight("MiniTablineHidden", { fg = palette.gray, bg = palette.darker_gray })
	highlight("MiniTablineModifiedCurrent", { fg = palette.yellow, bg = palette.dark_gray })
	highlight("MiniTablineModifiedHidden", { fg = palette.yellow, bg = palette.darker_gray })
	highlight("MiniTablineModifiedVisible", { fg = palette.yellow, bg = palette.dark_gray })
	highlight("MiniTablineTabpagesection", { fg = palette.bg, bg = palette.blue })
	highlight("MiniTablineVisible", { fg = palette.fg, bg = palette.dark_gray })
	highlight("MiniTestEmphasis", { bold = true })
	highlight("MiniTestFail", { fg = palette.red, bold = true })
	highlight("MiniTestPass", { fg = palette.green, bold = true })
	highlight("MiniTrailspace", { bg = palette.red })
end

return M
