local M = {}

function M.setup(highlight, palette)
	highlight("NavicIconsFile", { fg = palette.fg })
	highlight("NavicIconsModule", { fg = palette.yellow })
	highlight("NavicIconsNamespace", { fg = palette.cyan })
	highlight("NavicIconsPackage", { fg = palette.purple })
	highlight("NavicIconsClass", { fg = palette.orange })
	highlight("NavicIconsMethod", { fg = palette.blue })
	highlight("NavicIconsProperty", { fg = palette.green })
	highlight("NavicIconsField", { fg = palette.green })
	highlight("NavicIconsConstructor", { fg = palette.orange })
	highlight("NavicIconsEnum", { fg = palette.purple })
	highlight("NavicIconsInterface", { fg = palette.cyan })
	highlight("NavicIconsFunction", { fg = palette.blue })
	highlight("NavicIconsVariable", { fg = palette.red })
	highlight("NavicIconsConstant", { fg = palette.orange })
	highlight("NavicIconsString", { fg = palette.green })
	highlight("NavicIconsNumber", { fg = palette.orange })
	highlight("NavicIconsBoolean", { fg = palette.orange })
	highlight("NavicIconsArray", { fg = palette.purple })
	highlight("NavicIconsObject", { fg = palette.purple })
	highlight("NavicIconsKey", { fg = palette.purple })
	highlight("NavicIconsNull", { fg = palette.gray })
	highlight("NavicIconsEnumMember", { fg = palette.green })
	highlight("NavicIconsStruct", { fg = palette.purple })
	highlight("NavicIconsEvent", { fg = palette.yellow })
	highlight("NavicIconsOperator", { fg = palette.cyan })
	highlight("NavicIconsTypeParameter", { fg = palette.red })
	highlight("NavicText", { fg = palette.fg })
	highlight("NavicSeparator", { fg = palette.gray })
end

return M
