local M = {}

function M.setup(highlight, palette)
	highlight("TSAnnotation", { fg = palette.yellow })
	highlight("TSAttribute", { fg = palette.cyan })
	highlight("TSBoolean", { fg = palette.orange })
	highlight("TSCharacter", { fg = palette.green })
	highlight("TSComment", { fg = palette.gray, italic = true })
	highlight("TSConditional", { fg = palette.purple })
	highlight("TSConstant", { fg = palette.cyan })
	highlight("TSConstBuiltin", { fg = palette.orange })
	highlight("TSConstMacro", { fg = palette.orange })
	highlight("TSError", { fg = palette.red })
	highlight("TSException", { fg = palette.purple })
	highlight("TSField", { fg = palette.red })
	highlight("TSFloat", { fg = palette.orange })
	highlight("TSFunction", { fg = palette.blue })
	highlight("TSFuncBuiltin", { fg = palette.cyan })
	highlight("TSFuncMacro", { fg = palette.blue })
	highlight("TSInclude", { fg = palette.purple })
	highlight("TSKeyword", { fg = palette.purple })
	highlight("TSKeywordFunction", { fg = palette.purple })
	highlight("TSKeywordOperator", { fg = palette.cyan })
	highlight("TSLabel", { fg = palette.red })
	highlight("TSMethod", { fg = palette.blue })
	highlight("TSNamespace", { fg = palette.yellow })
	highlight("TSNone", { fg = palette.fg })
	highlight("TSNumber", { fg = palette.orange })
	highlight("TSOperator", { fg = palette.cyan })
	highlight("TSParameter", { fg = palette.red })
	highlight("TSParameterReference", { fg = palette.red })
	highlight("TSProperty", { fg = palette.red })
	highlight("TSPunctDelimiter", { fg = palette.fg })
	highlight("TSPunctBracket", { fg = palette.fg })
	highlight("TSPunctSpecial", { fg = palette.cyan })
	highlight("TSRepeat", { fg = palette.purple })
	highlight("TSString", { fg = palette.green })
	highlight("TSStringRegex", { fg = palette.orange })
	highlight("TSStringEscape", { fg = palette.orange })
	highlight("TSSymbol", { fg = palette.cyan })
	highlight("TSTag", { fg = palette.blue })
	highlight("TSTagDelimiter", { fg = palette.gray })
	highlight("TSText", { fg = palette.fg })
	highlight("TSStrong", { bold = true })
	highlight("TSEmphasis", { italic = true })
	highlight("TSUnderline", { underline = true })
	highlight("TSStrike", { strikethrough = true })
	highlight("TSTitle", { fg = palette.yellow, bold = true })
	highlight("TSLiteral", { fg = palette.green })
	highlight("TSURI", { fg = palette.blue, underline = true })
	highlight("TSType", { fg = palette.yellow })
	highlight("TSTypeBuiltin", { fg = palette.orange })
	highlight("TSVariable", { fg = palette.fg })
	highlight("TSVariableBuiltin", { fg = palette.orange })
	highlight("TreesitterContext", { bg = palette.dark_gray })
	highlight("TreesitterContextLineNumber", { fg = palette.gray })
end

return M
